[package]
name = "compactly-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
synstructure = "0.13.1"
quote = "1.0.38"
proc-macro2 = "1.0.92"

[dev-dependencies]
compactly = { path = ".." }
cabac.workspace = true